#!/usr/bin/env bash
set -e
# stories - Generate pages and index html from .ssv
# Required: coreutils(cp) sed
# This file should be in the same directory as: html.i html.s stories.ssv app/
ssv=stories.ssv

Story(){ # I:i,th,en,aud
	echo "<a href=\"$i.html\">$i. $th<br><i>$en</i><br></a>" >>app/index.html
	cp html.s "app/$i.html"
	if [[ -f $aud ]]
	then # Audio, do full js
		cat s.js >>"app/$i.html"
	else # No Audio
		sed -i 's/img src=/img border="3" src=/' "app/$i.html"
		echo "document.addEventListener('keypress', function(){location.href='index.html';});" >>"app/$i.html"
		echo "document.addEventListener('click', function(){location.href='index.html';});" >>"app/$i.html"
	fi
	echo "</script>" >>"app/$i.html"
	sed -i -e "s/%1/$i/" -e "s/%2/$th/" -e "s/%3/$en/" "app/$i.html"
}

[[ ${0//\/} = $0 ]] || cd ${0%/*}
cp html.i app/index.html
IFS=';'
while read i th en
do # Every line
	[[ $i ]] || continue
	[[ $th ]] || th=$i
	[[ $en ]] || en=$i
	aud=app/$i.mp3 img=app/$i.png
	[[ -f $img ]] &&
		Story && continue
	echo -n "Missing:"
	[[ -f $aud ]] || echo -n " $aud"
	[[ -f $img ]] || echo -n " $img"
	echo
done <"$ssv"
