#!/usr/bin/env bash
set -e
# stories - Generate pages and index html from .ssv
# Required: coreutils(cp) sed
# This file should be in the same directory as: html.i html.s stories.ssv app/
ssv=stories.ssv

Story(){ # I:i,th,en
	echo "<a href=\"$i.html\">$i. $th<br><i>$en</i><br></a>" >>app/index.html
	sed -e "s/%1/$i/" -e "s/%2/$th/" -e "s/%3/$en/" html.s >"app/$i.html"
}

[[ ${0//\/} = $0 ]] || cd ${0%/*}
cp html.i app/index.html
IFS=';'
while read i th en
do # Every line
	aud=app/$i.mp3 img=app/$i.png
	[[ -f $aud && -f $img ]] &&
		Story && continue
	echo -n "Missing:"
	[[ -f $aud ]] || echo -n " $aud"
	[[ -f $img ]] || echo -n " $img"
	echo
done <"$ssv"
